FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
python-pip python-dev python-opencv python-tk python-numpy \
git zip libopenblas-dev cmake zlib1g-dev

RUN git clone https://github.com/openai/atari-py /opt/atari-py \
&& cd /opt/atari-py \
&& git checkout 0.2.6

RUN git clone https://github.com/elsa-lab/option_critic.git /opt/option_critic \
&& cd /opt/option_critic \
&& bash option_critic/scripts/setup/install.sh
RUN sed -i s/gpu0/cpu/ /opt/option_critic/option_critic/scripts/train/_common/init_training_environment.sh \
&& sed -i '24,26d' /opt/option_critic/option_critic/scripts/train/_common/init_training_environment.sh \
&& sed -i '6,11d' /opt/option_critic/option_critic/scripts/train/_common/init_training_environment.sh \
&& sed -i s/dnn_type=self.params.USE_DNN_TYPE/dnn_type=False/ /opt/option_critic/option_critic/train_agent.py

RUN mv /opt/atari-py/atari_py/atari_roms /opt/option_critic/roms \
&& rm -r /opt/atari-py

WORKDIR /opt/option_critic

